# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run our test lane"
  lane :tests do
    #cocoapods(use_bundle_exec: false)
    run_tests(
      #workspace: "Travis1.xcworkspace",
      #scheme: "Travis1Tests",
      scheme: "Travis1",
      #devices: ["iPhone 5s", "iPhone X", "iPad Pro (12.9-inch)"],
      #devices: ["iPhone 5s iOS 11.2"], #not ok locally
      devices: ["iPhone 5s iOS 11.3"], #ok locally
      clean: false
    )
  end
end
